CREATE DATABASE GAME_SERVICE;
USE GAME_SERVICE

CREATE TABLE PLAYERS (
PID INT NOT NULL AUTO_INCREMENT,
ACCOUNT VARCHAR(25) UNIQUE NOT NULL,
PASSWORD VARCHAR(25) NOT NULL,
NICKNAME VARCHAR(20) UNIQUE NOT NULL,
CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
LASTLOGIN TIMESTAMP,
ISBANED TINYINT(1) DEFAULT FALSE,
PRIMARY KEY(PID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE PLAYER_INFO (
PID INT NOT NULL,
NICKNAME VARCHAR(20) UNIQUE NOT NULL,
GOLD INT,
CUR_SCENE SMALLINT,
CUR_POS_X SMALLINT,
CUR_POS_Y SMALLINT,
HP INT,
FOREIGN KEY(PID) REFERENCES PLAYERS(PID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE RESOURCE_LIST (
RID INT,
TYPE INT,
RES_NAME VARCHAR(50),
DESCRIPTION VARCHAR(256),
PRIMARY KEY(RID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE PLAYER_RES (
PID INT NOT NULL,
RID INT NOT NULL,
NUMBER INT NOT NULL,
FOREIGN KEY(PID) REFERENCES PLAYERS(PID),
FOREIGN KEY(RID) REFERENCES RESOURCE_LIST(RID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE MARKET_RES (
ITEMID INT AUTO_INCREMENT,
PID INT NOT NULL,
RID INT NOT NULL,
NUMBER INT NOT NULL,
UNIT_PRICE INT NOT NULL,
CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(PID) REFERENCES PLAYERS(PID),
FOREIGN KEY(RID) REFERENCES RESOURCE_LIST(RID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE SHIP_LIST (
SHIPID INT NOT NULL,
SHIP_NAME VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(256),
PRIMARY KEY(SHIPID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE PLAYER_SHIP (
PID INT NOT NULL,
SHIPID INT NOT NULL,
LEVEL INT NOT NULL,
EXP INT NOT NULL,
DETAIL VARCHAR(256),
FOREIGN KEY(PID) REFERENCES PLAYERS(PID),
FOREIGN KEY(SHIPID) REFERENCES SHIP_LIST(SHIPID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
