// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource.proto

package org.tont.proto;

public final class PlayerOwnedRes {
  private PlayerOwnedRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ResEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string resId = 1;</code>
     */
    java.lang.String getResId();
    /**
     * <code>optional string resId = 1;</code>
     */
    com.google.protobuf.ByteString
        getResIdBytes();

    /**
     * <code>optional string resName = 2;</code>
     */
    java.lang.String getResName();
    /**
     * <code>optional string resName = 2;</code>
     */
    com.google.protobuf.ByteString
        getResNameBytes();

    /**
     * <code>optional string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional int32 num = 4;</code>
     */
    int getNum();
  }
  /**
   * Protobuf type {@code proto.ResEntity}
   *
   * <pre>
   * [START messages]
   * </pre>
   */
  public  static final class ResEntity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.ResEntity)
      ResEntityOrBuilder {
    // Use ResEntity.newBuilder() to construct.
    private ResEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResEntity() {
      resId_ = "";
      resName_ = "";
      description_ = "";
      num_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              resId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              resName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 32: {

              num_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tont.proto.PlayerOwnedRes.internal_static_proto_ResEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tont.proto.PlayerOwnedRes.internal_static_proto_ResEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tont.proto.PlayerOwnedRes.ResEntity.class, org.tont.proto.PlayerOwnedRes.ResEntity.Builder.class);
    }

    public static final int RESID_FIELD_NUMBER = 1;
    private volatile java.lang.Object resId_;
    /**
     * <code>optional string resId = 1;</code>
     */
    public java.lang.String getResId() {
      java.lang.Object ref = resId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string resId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResIdBytes() {
      java.lang.Object ref = resId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object resName_;
    /**
     * <code>optional string resName = 2;</code>
     */
    public java.lang.String getResName() {
      java.lang.Object ref = resName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string resName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResNameBytes() {
      java.lang.Object ref = resName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>optional string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUM_FIELD_NUMBER = 4;
    private int num_;
    /**
     * <code>optional int32 num = 4;</code>
     */
    public int getNum() {
      return num_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, resId_);
      }
      if (!getResNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, resName_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
      }
      if (num_ != 0) {
        output.writeInt32(4, num_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, resId_);
      }
      if (!getResNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, resName_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, num_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.PlayerOwnedRes.ResEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tont.proto.PlayerOwnedRes.ResEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ResEntity}
     *
     * <pre>
     * [START messages]
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ResEntity)
        org.tont.proto.PlayerOwnedRes.ResEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.PlayerOwnedRes.internal_static_proto_ResEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.PlayerOwnedRes.internal_static_proto_ResEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.PlayerOwnedRes.ResEntity.class, org.tont.proto.PlayerOwnedRes.ResEntity.Builder.class);
      }

      // Construct using org.tont.proto.PlayerOwnedRes.ResEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resId_ = "";

        resName_ = "";

        description_ = "";

        num_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tont.proto.PlayerOwnedRes.internal_static_proto_ResEntity_descriptor;
      }

      public org.tont.proto.PlayerOwnedRes.ResEntity getDefaultInstanceForType() {
        return org.tont.proto.PlayerOwnedRes.ResEntity.getDefaultInstance();
      }

      public org.tont.proto.PlayerOwnedRes.ResEntity build() {
        org.tont.proto.PlayerOwnedRes.ResEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tont.proto.PlayerOwnedRes.ResEntity buildPartial() {
        org.tont.proto.PlayerOwnedRes.ResEntity result = new org.tont.proto.PlayerOwnedRes.ResEntity(this);
        result.resId_ = resId_;
        result.resName_ = resName_;
        result.description_ = description_;
        result.num_ = num_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tont.proto.PlayerOwnedRes.ResEntity) {
          return mergeFrom((org.tont.proto.PlayerOwnedRes.ResEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tont.proto.PlayerOwnedRes.ResEntity other) {
        if (other == org.tont.proto.PlayerOwnedRes.ResEntity.getDefaultInstance()) return this;
        if (!other.getResId().isEmpty()) {
          resId_ = other.resId_;
          onChanged();
        }
        if (!other.getResName().isEmpty()) {
          resName_ = other.resName_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tont.proto.PlayerOwnedRes.ResEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tont.proto.PlayerOwnedRes.ResEntity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object resId_ = "";
      /**
       * <code>optional string resId = 1;</code>
       */
      public java.lang.String getResId() {
        java.lang.Object ref = resId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResIdBytes() {
        java.lang.Object ref = resId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resId = 1;</code>
       */
      public Builder setResId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resId = 1;</code>
       */
      public Builder clearResId() {
        
        resId_ = getDefaultInstance().getResId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resId = 1;</code>
       */
      public Builder setResIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resName_ = "";
      /**
       * <code>optional string resName = 2;</code>
       */
      public java.lang.String getResName() {
        java.lang.Object ref = resName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResNameBytes() {
        java.lang.Object ref = resName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resName = 2;</code>
       */
      public Builder setResName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resName = 2;</code>
       */
      public Builder clearResName() {
        
        resName_ = getDefaultInstance().getResName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resName = 2;</code>
       */
      public Builder setResNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <code>optional int32 num = 4;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional int32 num = 4;</code>
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num = 4;</code>
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ResEntity)
    }

    // @@protoc_insertion_point(class_scope:proto.ResEntity)
    private static final org.tont.proto.PlayerOwnedRes.ResEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tont.proto.PlayerOwnedRes.ResEntity();
    }

    public static org.tont.proto.PlayerOwnedRes.ResEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResEntity>
        PARSER = new com.google.protobuf.AbstractParser<ResEntity>() {
      public ResEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ResEntity(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ResEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResEntity> getParserForType() {
      return PARSER;
    }

    public org.tont.proto.PlayerOwnedRes.ResEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResourcesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Resources)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; resMap = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getResMap();
  }
  /**
   * Protobuf type {@code proto.Resources}
   */
  public  static final class Resources extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Resources)
      ResourcesOrBuilder {
    // Use Resources.newBuilder() to construct.
    private Resources(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Resources() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Resources(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                resMap_ = com.google.protobuf.MapField.newMapField(
                    ResMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              resMap = input.readMessage(
                  ResMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              resMap_.getMutableMap().put(resMap.getKey(), resMap.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tont.proto.PlayerOwnedRes.internal_static_proto_Resources_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetResMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tont.proto.PlayerOwnedRes.internal_static_proto_Resources_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tont.proto.PlayerOwnedRes.Resources.class, org.tont.proto.PlayerOwnedRes.Resources.Builder.class);
    }

    public static final int RESMAP_FIELD_NUMBER = 1;
    private static final class ResMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.tont.proto.PlayerOwnedRes.internal_static_proto_Resources_ResMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> resMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetResMap() {
      if (resMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResMapDefaultEntryHolder.defaultEntry);
     }
      return resMap_;
    }
    /**
     * <code>map&lt;string, string&gt; resMap = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getResMap() {
      return internalGetResMap().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetResMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        resMap = ResMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, resMap);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetResMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        resMap = ResMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, resMap);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tont.proto.PlayerOwnedRes.Resources parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.PlayerOwnedRes.Resources parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tont.proto.PlayerOwnedRes.Resources prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Resources}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Resources)
        org.tont.proto.PlayerOwnedRes.ResourcesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.PlayerOwnedRes.internal_static_proto_Resources_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetResMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableResMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.PlayerOwnedRes.internal_static_proto_Resources_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.PlayerOwnedRes.Resources.class, org.tont.proto.PlayerOwnedRes.Resources.Builder.class);
      }

      // Construct using org.tont.proto.PlayerOwnedRes.Resources.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableResMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tont.proto.PlayerOwnedRes.internal_static_proto_Resources_descriptor;
      }

      public org.tont.proto.PlayerOwnedRes.Resources getDefaultInstanceForType() {
        return org.tont.proto.PlayerOwnedRes.Resources.getDefaultInstance();
      }

      public org.tont.proto.PlayerOwnedRes.Resources build() {
        org.tont.proto.PlayerOwnedRes.Resources result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tont.proto.PlayerOwnedRes.Resources buildPartial() {
        org.tont.proto.PlayerOwnedRes.Resources result = new org.tont.proto.PlayerOwnedRes.Resources(this);
        int from_bitField0_ = bitField0_;
        result.resMap_ = internalGetResMap();
        result.resMap_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tont.proto.PlayerOwnedRes.Resources) {
          return mergeFrom((org.tont.proto.PlayerOwnedRes.Resources)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tont.proto.PlayerOwnedRes.Resources other) {
        if (other == org.tont.proto.PlayerOwnedRes.Resources.getDefaultInstance()) return this;
        internalGetMutableResMap().mergeFrom(
            other.internalGetResMap());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tont.proto.PlayerOwnedRes.Resources parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tont.proto.PlayerOwnedRes.Resources) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> resMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetResMap() {
        if (resMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ResMapDefaultEntryHolder.defaultEntry);
       }
        return resMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableResMap() {
        onChanged();;
        if (resMap_ == null) {
          resMap_ = com.google.protobuf.MapField.newMapField(
              ResMapDefaultEntryHolder.defaultEntry);
        }
        if (!resMap_.isMutable()) {
          resMap_ = resMap_.copy();
        }
        return resMap_;
      }
      /**
       * <code>map&lt;string, string&gt; resMap = 1;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getResMap() {
        return internalGetResMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; resMap = 1;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableResMap() {
        return internalGetMutableResMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; resMap = 1;</code>
       */
      public Builder putAllResMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableResMap().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Resources)
    }

    // @@protoc_insertion_point(class_scope:proto.Resources)
    private static final org.tont.proto.PlayerOwnedRes.Resources DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tont.proto.PlayerOwnedRes.Resources();
    }

    public static org.tont.proto.PlayerOwnedRes.Resources getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Resources>
        PARSER = new com.google.protobuf.AbstractParser<Resources>() {
      public Resources parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Resources(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Resources> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Resources> getParserForType() {
      return PARSER;
    }

    public org.tont.proto.PlayerOwnedRes.Resources getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ResEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ResEntity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Resources_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Resources_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Resources_ResMapEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Resources_ResMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016resource.proto\022\005proto\"M\n\tResEntity\022\r\n\005" +
      "resId\030\001 \001(\t\022\017\n\007resName\030\002 \001(\t\022\023\n\013descript" +
      "ion\030\003 \001(\t\022\013\n\003num\030\004 \001(\005\"h\n\tResources\022,\n\006r" +
      "esMap\030\001 \003(\0132\034.proto.Resources.ResMapEntr" +
      "y\032-\n\013ResMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001BF\n\016org.tont.protoB\016PlayerOwnedR" +
      "es\252\002#Google.Protobuf.ToNT.PlayerOwnedRes" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ResEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ResEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ResEntity_descriptor,
        new java.lang.String[] { "ResId", "ResName", "Description", "Num", });
    internal_static_proto_Resources_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Resources_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Resources_descriptor,
        new java.lang.String[] { "ResMap", });
    internal_static_proto_Resources_ResMapEntry_descriptor =
      internal_static_proto_Resources_descriptor.getNestedTypes().get(0);
    internal_static_proto_Resources_ResMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Resources_ResMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
