// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playerMove.proto

package org.tont.proto;

public final class MoveBroadcast {
  private MoveBroadcast() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MoveEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MoveEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 pid = 1;</code>
     */
    int getPid();

    /**
     * <code>optional int32 sceneId = 2;</code>
     */
    int getSceneId();

    /**
     * <code>optional int32 moveSeq = 3;</code>
     */
    int getMoveSeq();

    /**
     * <code>optional int32 posFromX = 6;</code>
     */
    int getPosFromX();

    /**
     * <code>optional int32 posFromY = 7;</code>
     */
    int getPosFromY();

    /**
     * <code>optional int32 posToX = 8;</code>
     */
    int getPosToX();

    /**
     * <code>optional int32 posToY = 9;</code>
     */
    int getPosToY();

    /**
     * <code>optional int32 posCurrentX = 10;</code>
     */
    int getPosCurrentX();

    /**
     * <code>optional int32 posCurrentY = 11;</code>
     */
    int getPosCurrentY();

    /**
     * <code>optional int64 time = 12;</code>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code proto.MoveEntity}
   *
   * <pre>
   * [广播给玩家的场景内所有玩家的移动信息]
   * [START messages : code 410,411,412,420]
   * </pre>
   */
  public  static final class MoveEntity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.MoveEntity)
      MoveEntityOrBuilder {
    // Use MoveEntity.newBuilder() to construct.
    private MoveEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MoveEntity() {
      pid_ = 0;
      sceneId_ = 0;
      moveSeq_ = 0;
      posFromX_ = 0;
      posFromY_ = 0;
      posToX_ = 0;
      posToY_ = 0;
      posCurrentX_ = 0;
      posCurrentY_ = 0;
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MoveEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              pid_ = input.readInt32();
              break;
            }
            case 16: {

              sceneId_ = input.readInt32();
              break;
            }
            case 24: {

              moveSeq_ = input.readInt32();
              break;
            }
            case 48: {

              posFromX_ = input.readInt32();
              break;
            }
            case 56: {

              posFromY_ = input.readInt32();
              break;
            }
            case 64: {

              posToX_ = input.readInt32();
              break;
            }
            case 72: {

              posToY_ = input.readInt32();
              break;
            }
            case 80: {

              posCurrentX_ = input.readInt32();
              break;
            }
            case 88: {

              posCurrentY_ = input.readInt32();
              break;
            }
            case 96: {

              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tont.proto.MoveBroadcast.internal_static_proto_MoveEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tont.proto.MoveBroadcast.internal_static_proto_MoveEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tont.proto.MoveBroadcast.MoveEntity.class, org.tont.proto.MoveBroadcast.MoveEntity.Builder.class);
    }

    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    /**
     * <code>optional int32 pid = 1;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int SCENEID_FIELD_NUMBER = 2;
    private int sceneId_;
    /**
     * <code>optional int32 sceneId = 2;</code>
     */
    public int getSceneId() {
      return sceneId_;
    }

    public static final int MOVESEQ_FIELD_NUMBER = 3;
    private int moveSeq_;
    /**
     * <code>optional int32 moveSeq = 3;</code>
     */
    public int getMoveSeq() {
      return moveSeq_;
    }

    public static final int POSFROMX_FIELD_NUMBER = 6;
    private int posFromX_;
    /**
     * <code>optional int32 posFromX = 6;</code>
     */
    public int getPosFromX() {
      return posFromX_;
    }

    public static final int POSFROMY_FIELD_NUMBER = 7;
    private int posFromY_;
    /**
     * <code>optional int32 posFromY = 7;</code>
     */
    public int getPosFromY() {
      return posFromY_;
    }

    public static final int POSTOX_FIELD_NUMBER = 8;
    private int posToX_;
    /**
     * <code>optional int32 posToX = 8;</code>
     */
    public int getPosToX() {
      return posToX_;
    }

    public static final int POSTOY_FIELD_NUMBER = 9;
    private int posToY_;
    /**
     * <code>optional int32 posToY = 9;</code>
     */
    public int getPosToY() {
      return posToY_;
    }

    public static final int POSCURRENTX_FIELD_NUMBER = 10;
    private int posCurrentX_;
    /**
     * <code>optional int32 posCurrentX = 10;</code>
     */
    public int getPosCurrentX() {
      return posCurrentX_;
    }

    public static final int POSCURRENTY_FIELD_NUMBER = 11;
    private int posCurrentY_;
    /**
     * <code>optional int32 posCurrentY = 11;</code>
     */
    public int getPosCurrentY() {
      return posCurrentY_;
    }

    public static final int TIME_FIELD_NUMBER = 12;
    private long time_;
    /**
     * <code>optional int64 time = 12;</code>
     */
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pid_ != 0) {
        output.writeInt32(1, pid_);
      }
      if (sceneId_ != 0) {
        output.writeInt32(2, sceneId_);
      }
      if (moveSeq_ != 0) {
        output.writeInt32(3, moveSeq_);
      }
      if (posFromX_ != 0) {
        output.writeInt32(6, posFromX_);
      }
      if (posFromY_ != 0) {
        output.writeInt32(7, posFromY_);
      }
      if (posToX_ != 0) {
        output.writeInt32(8, posToX_);
      }
      if (posToY_ != 0) {
        output.writeInt32(9, posToY_);
      }
      if (posCurrentX_ != 0) {
        output.writeInt32(10, posCurrentX_);
      }
      if (posCurrentY_ != 0) {
        output.writeInt32(11, posCurrentY_);
      }
      if (time_ != 0L) {
        output.writeInt64(12, time_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pid_);
      }
      if (sceneId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sceneId_);
      }
      if (moveSeq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, moveSeq_);
      }
      if (posFromX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, posFromX_);
      }
      if (posFromY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, posFromY_);
      }
      if (posToX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, posToX_);
      }
      if (posToY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, posToY_);
      }
      if (posCurrentX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, posCurrentX_);
      }
      if (posCurrentY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, posCurrentY_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, time_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tont.proto.MoveBroadcast.MoveEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.MoveEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tont.proto.MoveBroadcast.MoveEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MoveEntity}
     *
     * <pre>
     * [广播给玩家的场景内所有玩家的移动信息]
     * [START messages : code 410,411,412,420]
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MoveEntity)
        org.tont.proto.MoveBroadcast.MoveEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_MoveEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_MoveEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.MoveBroadcast.MoveEntity.class, org.tont.proto.MoveBroadcast.MoveEntity.Builder.class);
      }

      // Construct using org.tont.proto.MoveBroadcast.MoveEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pid_ = 0;

        sceneId_ = 0;

        moveSeq_ = 0;

        posFromX_ = 0;

        posFromY_ = 0;

        posToX_ = 0;

        posToY_ = 0;

        posCurrentX_ = 0;

        posCurrentY_ = 0;

        time_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_MoveEntity_descriptor;
      }

      public org.tont.proto.MoveBroadcast.MoveEntity getDefaultInstanceForType() {
        return org.tont.proto.MoveBroadcast.MoveEntity.getDefaultInstance();
      }

      public org.tont.proto.MoveBroadcast.MoveEntity build() {
        org.tont.proto.MoveBroadcast.MoveEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tont.proto.MoveBroadcast.MoveEntity buildPartial() {
        org.tont.proto.MoveBroadcast.MoveEntity result = new org.tont.proto.MoveBroadcast.MoveEntity(this);
        result.pid_ = pid_;
        result.sceneId_ = sceneId_;
        result.moveSeq_ = moveSeq_;
        result.posFromX_ = posFromX_;
        result.posFromY_ = posFromY_;
        result.posToX_ = posToX_;
        result.posToY_ = posToY_;
        result.posCurrentX_ = posCurrentX_;
        result.posCurrentY_ = posCurrentY_;
        result.time_ = time_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tont.proto.MoveBroadcast.MoveEntity) {
          return mergeFrom((org.tont.proto.MoveBroadcast.MoveEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tont.proto.MoveBroadcast.MoveEntity other) {
        if (other == org.tont.proto.MoveBroadcast.MoveEntity.getDefaultInstance()) return this;
        if (other.getPid() != 0) {
          setPid(other.getPid());
        }
        if (other.getSceneId() != 0) {
          setSceneId(other.getSceneId());
        }
        if (other.getMoveSeq() != 0) {
          setMoveSeq(other.getMoveSeq());
        }
        if (other.getPosFromX() != 0) {
          setPosFromX(other.getPosFromX());
        }
        if (other.getPosFromY() != 0) {
          setPosFromY(other.getPosFromY());
        }
        if (other.getPosToX() != 0) {
          setPosToX(other.getPosToX());
        }
        if (other.getPosToY() != 0) {
          setPosToY(other.getPosToY());
        }
        if (other.getPosCurrentX() != 0) {
          setPosCurrentX(other.getPosCurrentX());
        }
        if (other.getPosCurrentY() != 0) {
          setPosCurrentY(other.getPosCurrentY());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tont.proto.MoveBroadcast.MoveEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tont.proto.MoveBroadcast.MoveEntity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pid_ ;
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public Builder clearPid() {
        
        pid_ = 0;
        onChanged();
        return this;
      }

      private int sceneId_ ;
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public int getSceneId() {
        return sceneId_;
      }
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public Builder setSceneId(int value) {
        
        sceneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public Builder clearSceneId() {
        
        sceneId_ = 0;
        onChanged();
        return this;
      }

      private int moveSeq_ ;
      /**
       * <code>optional int32 moveSeq = 3;</code>
       */
      public int getMoveSeq() {
        return moveSeq_;
      }
      /**
       * <code>optional int32 moveSeq = 3;</code>
       */
      public Builder setMoveSeq(int value) {
        
        moveSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 moveSeq = 3;</code>
       */
      public Builder clearMoveSeq() {
        
        moveSeq_ = 0;
        onChanged();
        return this;
      }

      private int posFromX_ ;
      /**
       * <code>optional int32 posFromX = 6;</code>
       */
      public int getPosFromX() {
        return posFromX_;
      }
      /**
       * <code>optional int32 posFromX = 6;</code>
       */
      public Builder setPosFromX(int value) {
        
        posFromX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 posFromX = 6;</code>
       */
      public Builder clearPosFromX() {
        
        posFromX_ = 0;
        onChanged();
        return this;
      }

      private int posFromY_ ;
      /**
       * <code>optional int32 posFromY = 7;</code>
       */
      public int getPosFromY() {
        return posFromY_;
      }
      /**
       * <code>optional int32 posFromY = 7;</code>
       */
      public Builder setPosFromY(int value) {
        
        posFromY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 posFromY = 7;</code>
       */
      public Builder clearPosFromY() {
        
        posFromY_ = 0;
        onChanged();
        return this;
      }

      private int posToX_ ;
      /**
       * <code>optional int32 posToX = 8;</code>
       */
      public int getPosToX() {
        return posToX_;
      }
      /**
       * <code>optional int32 posToX = 8;</code>
       */
      public Builder setPosToX(int value) {
        
        posToX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 posToX = 8;</code>
       */
      public Builder clearPosToX() {
        
        posToX_ = 0;
        onChanged();
        return this;
      }

      private int posToY_ ;
      /**
       * <code>optional int32 posToY = 9;</code>
       */
      public int getPosToY() {
        return posToY_;
      }
      /**
       * <code>optional int32 posToY = 9;</code>
       */
      public Builder setPosToY(int value) {
        
        posToY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 posToY = 9;</code>
       */
      public Builder clearPosToY() {
        
        posToY_ = 0;
        onChanged();
        return this;
      }

      private int posCurrentX_ ;
      /**
       * <code>optional int32 posCurrentX = 10;</code>
       */
      public int getPosCurrentX() {
        return posCurrentX_;
      }
      /**
       * <code>optional int32 posCurrentX = 10;</code>
       */
      public Builder setPosCurrentX(int value) {
        
        posCurrentX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 posCurrentX = 10;</code>
       */
      public Builder clearPosCurrentX() {
        
        posCurrentX_ = 0;
        onChanged();
        return this;
      }

      private int posCurrentY_ ;
      /**
       * <code>optional int32 posCurrentY = 11;</code>
       */
      public int getPosCurrentY() {
        return posCurrentY_;
      }
      /**
       * <code>optional int32 posCurrentY = 11;</code>
       */
      public Builder setPosCurrentY(int value) {
        
        posCurrentY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 posCurrentY = 11;</code>
       */
      public Builder clearPosCurrentY() {
        
        posCurrentY_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 12;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 12;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 12;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.MoveEntity)
    }

    // @@protoc_insertion_point(class_scope:proto.MoveEntity)
    private static final org.tont.proto.MoveBroadcast.MoveEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tont.proto.MoveBroadcast.MoveEntity();
    }

    public static org.tont.proto.MoveBroadcast.MoveEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoveEntity>
        PARSER = new com.google.protobuf.AbstractParser<MoveEntity>() {
      public MoveEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MoveEntity(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MoveEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoveEntity> getParserForType() {
      return PARSER;
    }

    public org.tont.proto.MoveBroadcast.MoveEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SwitchSceneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SwitchScene)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 from = 1;</code>
     */
    int getFrom();

    /**
     * <code>optional int32 to = 2;</code>
     */
    int getTo();

    /**
     * <code>optional .proto.MoveEntity moveEntity = 3;</code>
     */
    boolean hasMoveEntity();
    /**
     * <code>optional .proto.MoveEntity moveEntity = 3;</code>
     */
    org.tont.proto.MoveBroadcast.MoveEntity getMoveEntity();
    /**
     * <code>optional .proto.MoveEntity moveEntity = 3;</code>
     */
    org.tont.proto.MoveBroadcast.MoveEntityOrBuilder getMoveEntityOrBuilder();
  }
  /**
   * Protobuf type {@code proto.SwitchScene}
   *
   * <pre>
   * [切换场景：from为-1表示进入场景界面，to为-1表示离开场景界面]
   * </pre>
   */
  public  static final class SwitchScene extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.SwitchScene)
      SwitchSceneOrBuilder {
    // Use SwitchScene.newBuilder() to construct.
    private SwitchScene(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SwitchScene() {
      from_ = 0;
      to_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SwitchScene(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              from_ = input.readInt32();
              break;
            }
            case 16: {

              to_ = input.readInt32();
              break;
            }
            case 26: {
              org.tont.proto.MoveBroadcast.MoveEntity.Builder subBuilder = null;
              if (moveEntity_ != null) {
                subBuilder = moveEntity_.toBuilder();
              }
              moveEntity_ = input.readMessage(org.tont.proto.MoveBroadcast.MoveEntity.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(moveEntity_);
                moveEntity_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tont.proto.MoveBroadcast.internal_static_proto_SwitchScene_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tont.proto.MoveBroadcast.internal_static_proto_SwitchScene_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tont.proto.MoveBroadcast.SwitchScene.class, org.tont.proto.MoveBroadcast.SwitchScene.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private int from_;
    /**
     * <code>optional int32 from = 1;</code>
     */
    public int getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private int to_;
    /**
     * <code>optional int32 to = 2;</code>
     */
    public int getTo() {
      return to_;
    }

    public static final int MOVEENTITY_FIELD_NUMBER = 3;
    private org.tont.proto.MoveBroadcast.MoveEntity moveEntity_;
    /**
     * <code>optional .proto.MoveEntity moveEntity = 3;</code>
     */
    public boolean hasMoveEntity() {
      return moveEntity_ != null;
    }
    /**
     * <code>optional .proto.MoveEntity moveEntity = 3;</code>
     */
    public org.tont.proto.MoveBroadcast.MoveEntity getMoveEntity() {
      return moveEntity_ == null ? org.tont.proto.MoveBroadcast.MoveEntity.getDefaultInstance() : moveEntity_;
    }
    /**
     * <code>optional .proto.MoveEntity moveEntity = 3;</code>
     */
    public org.tont.proto.MoveBroadcast.MoveEntityOrBuilder getMoveEntityOrBuilder() {
      return getMoveEntity();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != 0) {
        output.writeInt32(1, from_);
      }
      if (to_ != 0) {
        output.writeInt32(2, to_);
      }
      if (moveEntity_ != null) {
        output.writeMessage(3, getMoveEntity());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, from_);
      }
      if (to_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, to_);
      }
      if (moveEntity_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMoveEntity());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tont.proto.MoveBroadcast.SwitchScene parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.SwitchScene parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tont.proto.MoveBroadcast.SwitchScene prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SwitchScene}
     *
     * <pre>
     * [切换场景：from为-1表示进入场景界面，to为-1表示离开场景界面]
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SwitchScene)
        org.tont.proto.MoveBroadcast.SwitchSceneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_SwitchScene_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_SwitchScene_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.MoveBroadcast.SwitchScene.class, org.tont.proto.MoveBroadcast.SwitchScene.Builder.class);
      }

      // Construct using org.tont.proto.MoveBroadcast.SwitchScene.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        from_ = 0;

        to_ = 0;

        if (moveEntityBuilder_ == null) {
          moveEntity_ = null;
        } else {
          moveEntity_ = null;
          moveEntityBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_SwitchScene_descriptor;
      }

      public org.tont.proto.MoveBroadcast.SwitchScene getDefaultInstanceForType() {
        return org.tont.proto.MoveBroadcast.SwitchScene.getDefaultInstance();
      }

      public org.tont.proto.MoveBroadcast.SwitchScene build() {
        org.tont.proto.MoveBroadcast.SwitchScene result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tont.proto.MoveBroadcast.SwitchScene buildPartial() {
        org.tont.proto.MoveBroadcast.SwitchScene result = new org.tont.proto.MoveBroadcast.SwitchScene(this);
        result.from_ = from_;
        result.to_ = to_;
        if (moveEntityBuilder_ == null) {
          result.moveEntity_ = moveEntity_;
        } else {
          result.moveEntity_ = moveEntityBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tont.proto.MoveBroadcast.SwitchScene) {
          return mergeFrom((org.tont.proto.MoveBroadcast.SwitchScene)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tont.proto.MoveBroadcast.SwitchScene other) {
        if (other == org.tont.proto.MoveBroadcast.SwitchScene.getDefaultInstance()) return this;
        if (other.getFrom() != 0) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != 0) {
          setTo(other.getTo());
        }
        if (other.hasMoveEntity()) {
          mergeMoveEntity(other.getMoveEntity());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tont.proto.MoveBroadcast.SwitchScene parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tont.proto.MoveBroadcast.SwitchScene) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int from_ ;
      /**
       * <code>optional int32 from = 1;</code>
       */
      public int getFrom() {
        return from_;
      }
      /**
       * <code>optional int32 from = 1;</code>
       */
      public Builder setFrom(int value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int to_ ;
      /**
       * <code>optional int32 to = 2;</code>
       */
      public int getTo() {
        return to_;
      }
      /**
       * <code>optional int32 to = 2;</code>
       */
      public Builder setTo(int value) {
        
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = 0;
        onChanged();
        return this;
      }

      private org.tont.proto.MoveBroadcast.MoveEntity moveEntity_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          org.tont.proto.MoveBroadcast.MoveEntity, org.tont.proto.MoveBroadcast.MoveEntity.Builder, org.tont.proto.MoveBroadcast.MoveEntityOrBuilder> moveEntityBuilder_;
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      public boolean hasMoveEntity() {
        return moveEntityBuilder_ != null || moveEntity_ != null;
      }
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      public org.tont.proto.MoveBroadcast.MoveEntity getMoveEntity() {
        if (moveEntityBuilder_ == null) {
          return moveEntity_ == null ? org.tont.proto.MoveBroadcast.MoveEntity.getDefaultInstance() : moveEntity_;
        } else {
          return moveEntityBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      public Builder setMoveEntity(org.tont.proto.MoveBroadcast.MoveEntity value) {
        if (moveEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          moveEntity_ = value;
          onChanged();
        } else {
          moveEntityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      public Builder setMoveEntity(
          org.tont.proto.MoveBroadcast.MoveEntity.Builder builderForValue) {
        if (moveEntityBuilder_ == null) {
          moveEntity_ = builderForValue.build();
          onChanged();
        } else {
          moveEntityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      public Builder mergeMoveEntity(org.tont.proto.MoveBroadcast.MoveEntity value) {
        if (moveEntityBuilder_ == null) {
          if (moveEntity_ != null) {
            moveEntity_ =
              org.tont.proto.MoveBroadcast.MoveEntity.newBuilder(moveEntity_).mergeFrom(value).buildPartial();
          } else {
            moveEntity_ = value;
          }
          onChanged();
        } else {
          moveEntityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      public Builder clearMoveEntity() {
        if (moveEntityBuilder_ == null) {
          moveEntity_ = null;
          onChanged();
        } else {
          moveEntity_ = null;
          moveEntityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      public org.tont.proto.MoveBroadcast.MoveEntity.Builder getMoveEntityBuilder() {
        
        onChanged();
        return getMoveEntityFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      public org.tont.proto.MoveBroadcast.MoveEntityOrBuilder getMoveEntityOrBuilder() {
        if (moveEntityBuilder_ != null) {
          return moveEntityBuilder_.getMessageOrBuilder();
        } else {
          return moveEntity_ == null ?
              org.tont.proto.MoveBroadcast.MoveEntity.getDefaultInstance() : moveEntity_;
        }
      }
      /**
       * <code>optional .proto.MoveEntity moveEntity = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.tont.proto.MoveBroadcast.MoveEntity, org.tont.proto.MoveBroadcast.MoveEntity.Builder, org.tont.proto.MoveBroadcast.MoveEntityOrBuilder> 
          getMoveEntityFieldBuilder() {
        if (moveEntityBuilder_ == null) {
          moveEntityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.tont.proto.MoveBroadcast.MoveEntity, org.tont.proto.MoveBroadcast.MoveEntity.Builder, org.tont.proto.MoveBroadcast.MoveEntityOrBuilder>(
                  getMoveEntity(),
                  getParentForChildren(),
                  isClean());
          moveEntity_ = null;
        }
        return moveEntityBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.SwitchScene)
    }

    // @@protoc_insertion_point(class_scope:proto.SwitchScene)
    private static final org.tont.proto.MoveBroadcast.SwitchScene DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tont.proto.MoveBroadcast.SwitchScene();
    }

    public static org.tont.proto.MoveBroadcast.SwitchScene getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SwitchScene>
        PARSER = new com.google.protobuf.AbstractParser<SwitchScene>() {
      public SwitchScene parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SwitchScene(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<SwitchScene> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SwitchScene> getParserForType() {
      return PARSER;
    }

    public org.tont.proto.MoveBroadcast.SwitchScene getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MoveBroadcastPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MoveBroadcastPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.MoveEntity move = 1;</code>
     */
    boolean hasMove();
    /**
     * <code>optional .proto.MoveEntity move = 1;</code>
     */
    org.tont.proto.MoveBroadcast.MoveEntity getMove();
    /**
     * <code>optional .proto.MoveEntity move = 1;</code>
     */
    org.tont.proto.MoveBroadcast.MoveEntityOrBuilder getMoveOrBuilder();

    /**
     * <code>repeated int32 recId = 2;</code>
     */
    java.util.List<java.lang.Integer> getRecIdList();
    /**
     * <code>repeated int32 recId = 2;</code>
     */
    int getRecIdCount();
    /**
     * <code>repeated int32 recId = 2;</code>
     */
    int getRecId(int index);
  }
  /**
   * Protobuf type {@code proto.MoveBroadcastPacket}
   *
   * <pre>
   * [广播移动数据包]
   * </pre>
   */
  public  static final class MoveBroadcastPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.MoveBroadcastPacket)
      MoveBroadcastPacketOrBuilder {
    // Use MoveBroadcastPacket.newBuilder() to construct.
    private MoveBroadcastPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MoveBroadcastPacket() {
      recId_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MoveBroadcastPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.tont.proto.MoveBroadcast.MoveEntity.Builder subBuilder = null;
              if (move_ != null) {
                subBuilder = move_.toBuilder();
              }
              move_ = input.readMessage(org.tont.proto.MoveBroadcast.MoveEntity.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(move_);
                move_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                recId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              recId_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                recId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                recId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          recId_ = java.util.Collections.unmodifiableList(recId_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tont.proto.MoveBroadcast.internal_static_proto_MoveBroadcastPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tont.proto.MoveBroadcast.internal_static_proto_MoveBroadcastPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tont.proto.MoveBroadcast.MoveBroadcastPacket.class, org.tont.proto.MoveBroadcast.MoveBroadcastPacket.Builder.class);
    }

    private int bitField0_;
    public static final int MOVE_FIELD_NUMBER = 1;
    private org.tont.proto.MoveBroadcast.MoveEntity move_;
    /**
     * <code>optional .proto.MoveEntity move = 1;</code>
     */
    public boolean hasMove() {
      return move_ != null;
    }
    /**
     * <code>optional .proto.MoveEntity move = 1;</code>
     */
    public org.tont.proto.MoveBroadcast.MoveEntity getMove() {
      return move_ == null ? org.tont.proto.MoveBroadcast.MoveEntity.getDefaultInstance() : move_;
    }
    /**
     * <code>optional .proto.MoveEntity move = 1;</code>
     */
    public org.tont.proto.MoveBroadcast.MoveEntityOrBuilder getMoveOrBuilder() {
      return getMove();
    }

    public static final int RECID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> recId_;
    /**
     * <code>repeated int32 recId = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getRecIdList() {
      return recId_;
    }
    /**
     * <code>repeated int32 recId = 2;</code>
     */
    public int getRecIdCount() {
      return recId_.size();
    }
    /**
     * <code>repeated int32 recId = 2;</code>
     */
    public int getRecId(int index) {
      return recId_.get(index);
    }
    private int recIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (move_ != null) {
        output.writeMessage(1, getMove());
      }
      if (getRecIdList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(recIdMemoizedSerializedSize);
      }
      for (int i = 0; i < recId_.size(); i++) {
        output.writeInt32NoTag(recId_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (move_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMove());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < recId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(recId_.get(i));
        }
        size += dataSize;
        if (!getRecIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        recIdMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tont.proto.MoveBroadcast.MoveBroadcastPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MoveBroadcastPacket}
     *
     * <pre>
     * [广播移动数据包]
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MoveBroadcastPacket)
        org.tont.proto.MoveBroadcast.MoveBroadcastPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_MoveBroadcastPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_MoveBroadcastPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.MoveBroadcast.MoveBroadcastPacket.class, org.tont.proto.MoveBroadcast.MoveBroadcastPacket.Builder.class);
      }

      // Construct using org.tont.proto.MoveBroadcast.MoveBroadcastPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (moveBuilder_ == null) {
          move_ = null;
        } else {
          move_ = null;
          moveBuilder_ = null;
        }
        recId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tont.proto.MoveBroadcast.internal_static_proto_MoveBroadcastPacket_descriptor;
      }

      public org.tont.proto.MoveBroadcast.MoveBroadcastPacket getDefaultInstanceForType() {
        return org.tont.proto.MoveBroadcast.MoveBroadcastPacket.getDefaultInstance();
      }

      public org.tont.proto.MoveBroadcast.MoveBroadcastPacket build() {
        org.tont.proto.MoveBroadcast.MoveBroadcastPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tont.proto.MoveBroadcast.MoveBroadcastPacket buildPartial() {
        org.tont.proto.MoveBroadcast.MoveBroadcastPacket result = new org.tont.proto.MoveBroadcast.MoveBroadcastPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (moveBuilder_ == null) {
          result.move_ = move_;
        } else {
          result.move_ = moveBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          recId_ = java.util.Collections.unmodifiableList(recId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.recId_ = recId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tont.proto.MoveBroadcast.MoveBroadcastPacket) {
          return mergeFrom((org.tont.proto.MoveBroadcast.MoveBroadcastPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tont.proto.MoveBroadcast.MoveBroadcastPacket other) {
        if (other == org.tont.proto.MoveBroadcast.MoveBroadcastPacket.getDefaultInstance()) return this;
        if (other.hasMove()) {
          mergeMove(other.getMove());
        }
        if (!other.recId_.isEmpty()) {
          if (recId_.isEmpty()) {
            recId_ = other.recId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRecIdIsMutable();
            recId_.addAll(other.recId_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tont.proto.MoveBroadcast.MoveBroadcastPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tont.proto.MoveBroadcast.MoveBroadcastPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.tont.proto.MoveBroadcast.MoveEntity move_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          org.tont.proto.MoveBroadcast.MoveEntity, org.tont.proto.MoveBroadcast.MoveEntity.Builder, org.tont.proto.MoveBroadcast.MoveEntityOrBuilder> moveBuilder_;
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      public boolean hasMove() {
        return moveBuilder_ != null || move_ != null;
      }
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      public org.tont.proto.MoveBroadcast.MoveEntity getMove() {
        if (moveBuilder_ == null) {
          return move_ == null ? org.tont.proto.MoveBroadcast.MoveEntity.getDefaultInstance() : move_;
        } else {
          return moveBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      public Builder setMove(org.tont.proto.MoveBroadcast.MoveEntity value) {
        if (moveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          move_ = value;
          onChanged();
        } else {
          moveBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      public Builder setMove(
          org.tont.proto.MoveBroadcast.MoveEntity.Builder builderForValue) {
        if (moveBuilder_ == null) {
          move_ = builderForValue.build();
          onChanged();
        } else {
          moveBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      public Builder mergeMove(org.tont.proto.MoveBroadcast.MoveEntity value) {
        if (moveBuilder_ == null) {
          if (move_ != null) {
            move_ =
              org.tont.proto.MoveBroadcast.MoveEntity.newBuilder(move_).mergeFrom(value).buildPartial();
          } else {
            move_ = value;
          }
          onChanged();
        } else {
          moveBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      public Builder clearMove() {
        if (moveBuilder_ == null) {
          move_ = null;
          onChanged();
        } else {
          move_ = null;
          moveBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      public org.tont.proto.MoveBroadcast.MoveEntity.Builder getMoveBuilder() {
        
        onChanged();
        return getMoveFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      public org.tont.proto.MoveBroadcast.MoveEntityOrBuilder getMoveOrBuilder() {
        if (moveBuilder_ != null) {
          return moveBuilder_.getMessageOrBuilder();
        } else {
          return move_ == null ?
              org.tont.proto.MoveBroadcast.MoveEntity.getDefaultInstance() : move_;
        }
      }
      /**
       * <code>optional .proto.MoveEntity move = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.tont.proto.MoveBroadcast.MoveEntity, org.tont.proto.MoveBroadcast.MoveEntity.Builder, org.tont.proto.MoveBroadcast.MoveEntityOrBuilder> 
          getMoveFieldBuilder() {
        if (moveBuilder_ == null) {
          moveBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.tont.proto.MoveBroadcast.MoveEntity, org.tont.proto.MoveBroadcast.MoveEntity.Builder, org.tont.proto.MoveBroadcast.MoveEntityOrBuilder>(
                  getMove(),
                  getParentForChildren(),
                  isClean());
          move_ = null;
        }
        return moveBuilder_;
      }

      private java.util.List<java.lang.Integer> recId_ = java.util.Collections.emptyList();
      private void ensureRecIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          recId_ = new java.util.ArrayList<java.lang.Integer>(recId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 recId = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getRecIdList() {
        return java.util.Collections.unmodifiableList(recId_);
      }
      /**
       * <code>repeated int32 recId = 2;</code>
       */
      public int getRecIdCount() {
        return recId_.size();
      }
      /**
       * <code>repeated int32 recId = 2;</code>
       */
      public int getRecId(int index) {
        return recId_.get(index);
      }
      /**
       * <code>repeated int32 recId = 2;</code>
       */
      public Builder setRecId(
          int index, int value) {
        ensureRecIdIsMutable();
        recId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 recId = 2;</code>
       */
      public Builder addRecId(int value) {
        ensureRecIdIsMutable();
        recId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 recId = 2;</code>
       */
      public Builder addAllRecId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRecIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 recId = 2;</code>
       */
      public Builder clearRecId() {
        recId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.MoveBroadcastPacket)
    }

    // @@protoc_insertion_point(class_scope:proto.MoveBroadcastPacket)
    private static final org.tont.proto.MoveBroadcast.MoveBroadcastPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tont.proto.MoveBroadcast.MoveBroadcastPacket();
    }

    public static org.tont.proto.MoveBroadcast.MoveBroadcastPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoveBroadcastPacket>
        PARSER = new com.google.protobuf.AbstractParser<MoveBroadcastPacket>() {
      public MoveBroadcastPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MoveBroadcastPacket(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MoveBroadcastPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoveBroadcastPacket> getParserForType() {
      return PARSER;
    }

    public org.tont.proto.MoveBroadcast.MoveBroadcastPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MoveEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_MoveEntity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SwitchScene_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_SwitchScene_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MoveBroadcastPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_MoveBroadcastPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020playerMove.proto\022\005proto\"\267\001\n\nMoveEntity" +
      "\022\013\n\003pid\030\001 \001(\005\022\017\n\007sceneId\030\002 \001(\005\022\017\n\007moveSe" +
      "q\030\003 \001(\005\022\020\n\010posFromX\030\006 \001(\005\022\020\n\010posFromY\030\007 " +
      "\001(\005\022\016\n\006posToX\030\010 \001(\005\022\016\n\006posToY\030\t \001(\005\022\023\n\013p" +
      "osCurrentX\030\n \001(\005\022\023\n\013posCurrentY\030\013 \001(\005\022\014\n" +
      "\004time\030\014 \001(\003\"N\n\013SwitchScene\022\014\n\004from\030\001 \001(\005" +
      "\022\n\n\002to\030\002 \001(\005\022%\n\nmoveEntity\030\003 \001(\0132\021.proto" +
      ".MoveEntity\"E\n\023MoveBroadcastPacket\022\037\n\004mo" +
      "ve\030\001 \001(\0132\021.proto.MoveEntity\022\r\n\005recId\030\002 \003" +
      "(\005BD\n\016org.tont.protoB\rMoveBroadcast\252\002\"Go",
      "ogle.Protobuf.ToNT.MoveBroadcastb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_MoveEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MoveEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_MoveEntity_descriptor,
        new java.lang.String[] { "Pid", "SceneId", "MoveSeq", "PosFromX", "PosFromY", "PosToX", "PosToY", "PosCurrentX", "PosCurrentY", "Time", });
    internal_static_proto_SwitchScene_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SwitchScene_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_SwitchScene_descriptor,
        new java.lang.String[] { "From", "To", "MoveEntity", });
    internal_static_proto_MoveBroadcastPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_MoveBroadcastPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_MoveBroadcastPacket_descriptor,
        new java.lang.String[] { "Move", "RecId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
