// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playerShip.proto

package org.tont.proto;

public final class PlayerOwnedShip {
  private PlayerOwnedShip() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ShipEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ShipEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string shipId = 1;</code>
     */
    java.lang.String getShipId();
    /**
     * <code>optional string shipId = 1;</code>
     */
    com.google.protobuf.ByteString
        getShipIdBytes();

    /**
     * <code>optional string shipName = 2;</code>
     */
    java.lang.String getShipName();
    /**
     * <code>optional string shipName = 2;</code>
     */
    com.google.protobuf.ByteString
        getShipNameBytes();

    /**
     * <code>optional string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional int32 level = 4;</code>
     */
    int getLevel();

    /**
     * <code>optional int32 exp = 5;</code>
     */
    int getExp();

    /**
     * <code>optional string detail = 6;</code>
     */
    java.lang.String getDetail();
    /**
     * <code>optional string detail = 6;</code>
     */
    com.google.protobuf.ByteString
        getDetailBytes();
  }
  /**
   * Protobuf type {@code proto.ShipEntity}
   *
   * <pre>
   * [START messages]
   * </pre>
   */
  public  static final class ShipEntity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.ShipEntity)
      ShipEntityOrBuilder {
    // Use ShipEntity.newBuilder() to construct.
    private ShipEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ShipEntity() {
      shipId_ = "";
      shipName_ = "";
      description_ = "";
      level_ = 0;
      exp_ = 0;
      detail_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ShipEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              shipId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              shipName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 32: {

              level_ = input.readInt32();
              break;
            }
            case 40: {

              exp_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              detail_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tont.proto.PlayerOwnedShip.internal_static_proto_ShipEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tont.proto.PlayerOwnedShip.internal_static_proto_ShipEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tont.proto.PlayerOwnedShip.ShipEntity.class, org.tont.proto.PlayerOwnedShip.ShipEntity.Builder.class);
    }

    public static final int SHIPID_FIELD_NUMBER = 1;
    private volatile java.lang.Object shipId_;
    /**
     * <code>optional string shipId = 1;</code>
     */
    public java.lang.String getShipId() {
      java.lang.Object ref = shipId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shipId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string shipId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getShipIdBytes() {
      java.lang.Object ref = shipId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shipId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHIPNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object shipName_;
    /**
     * <code>optional string shipName = 2;</code>
     */
    public java.lang.String getShipName() {
      java.lang.Object ref = shipName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shipName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string shipName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getShipNameBytes() {
      java.lang.Object ref = shipName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shipName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>optional string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_;
    /**
     * <code>optional int32 level = 4;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int EXP_FIELD_NUMBER = 5;
    private int exp_;
    /**
     * <code>optional int32 exp = 5;</code>
     */
    public int getExp() {
      return exp_;
    }

    public static final int DETAIL_FIELD_NUMBER = 6;
    private volatile java.lang.Object detail_;
    /**
     * <code>optional string detail = 6;</code>
     */
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detail_ = s;
        return s;
      }
    }
    /**
     * <code>optional string detail = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getShipIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, shipId_);
      }
      if (!getShipNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, shipName_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
      }
      if (level_ != 0) {
        output.writeInt32(4, level_);
      }
      if (exp_ != 0) {
        output.writeInt32(5, exp_);
      }
      if (!getDetailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, detail_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getShipIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, shipId_);
      }
      if (!getShipNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, shipName_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      if (exp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, exp_);
      }
      if (!getDetailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, detail_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.PlayerOwnedShip.ShipEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tont.proto.PlayerOwnedShip.ShipEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ShipEntity}
     *
     * <pre>
     * [START messages]
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ShipEntity)
        org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.PlayerOwnedShip.internal_static_proto_ShipEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.PlayerOwnedShip.internal_static_proto_ShipEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.PlayerOwnedShip.ShipEntity.class, org.tont.proto.PlayerOwnedShip.ShipEntity.Builder.class);
      }

      // Construct using org.tont.proto.PlayerOwnedShip.ShipEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        shipId_ = "";

        shipName_ = "";

        description_ = "";

        level_ = 0;

        exp_ = 0;

        detail_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tont.proto.PlayerOwnedShip.internal_static_proto_ShipEntity_descriptor;
      }

      public org.tont.proto.PlayerOwnedShip.ShipEntity getDefaultInstanceForType() {
        return org.tont.proto.PlayerOwnedShip.ShipEntity.getDefaultInstance();
      }

      public org.tont.proto.PlayerOwnedShip.ShipEntity build() {
        org.tont.proto.PlayerOwnedShip.ShipEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tont.proto.PlayerOwnedShip.ShipEntity buildPartial() {
        org.tont.proto.PlayerOwnedShip.ShipEntity result = new org.tont.proto.PlayerOwnedShip.ShipEntity(this);
        result.shipId_ = shipId_;
        result.shipName_ = shipName_;
        result.description_ = description_;
        result.level_ = level_;
        result.exp_ = exp_;
        result.detail_ = detail_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tont.proto.PlayerOwnedShip.ShipEntity) {
          return mergeFrom((org.tont.proto.PlayerOwnedShip.ShipEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tont.proto.PlayerOwnedShip.ShipEntity other) {
        if (other == org.tont.proto.PlayerOwnedShip.ShipEntity.getDefaultInstance()) return this;
        if (!other.getShipId().isEmpty()) {
          shipId_ = other.shipId_;
          onChanged();
        }
        if (!other.getShipName().isEmpty()) {
          shipName_ = other.shipName_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getExp() != 0) {
          setExp(other.getExp());
        }
        if (!other.getDetail().isEmpty()) {
          detail_ = other.detail_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tont.proto.PlayerOwnedShip.ShipEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tont.proto.PlayerOwnedShip.ShipEntity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object shipId_ = "";
      /**
       * <code>optional string shipId = 1;</code>
       */
      public java.lang.String getShipId() {
        java.lang.Object ref = shipId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shipId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string shipId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getShipIdBytes() {
        java.lang.Object ref = shipId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shipId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string shipId = 1;</code>
       */
      public Builder setShipId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shipId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string shipId = 1;</code>
       */
      public Builder clearShipId() {
        
        shipId_ = getDefaultInstance().getShipId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string shipId = 1;</code>
       */
      public Builder setShipIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shipId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shipName_ = "";
      /**
       * <code>optional string shipName = 2;</code>
       */
      public java.lang.String getShipName() {
        java.lang.Object ref = shipName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shipName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string shipName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getShipNameBytes() {
        java.lang.Object ref = shipName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shipName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string shipName = 2;</code>
       */
      public Builder setShipName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shipName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string shipName = 2;</code>
       */
      public Builder clearShipName() {
        
        shipName_ = getDefaultInstance().getShipName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string shipName = 2;</code>
       */
      public Builder setShipNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shipName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>optional int32 level = 4;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 4;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 4;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int exp_ ;
      /**
       * <code>optional int32 exp = 5;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>optional int32 exp = 5;</code>
       */
      public Builder setExp(int value) {
        
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exp = 5;</code>
       */
      public Builder clearExp() {
        
        exp_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object detail_ = "";
      /**
       * <code>optional string detail = 6;</code>
       */
      public java.lang.String getDetail() {
        java.lang.Object ref = detail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          detail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string detail = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDetailBytes() {
        java.lang.Object ref = detail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          detail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string detail = 6;</code>
       */
      public Builder setDetail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        detail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string detail = 6;</code>
       */
      public Builder clearDetail() {
        
        detail_ = getDefaultInstance().getDetail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string detail = 6;</code>
       */
      public Builder setDetailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        detail_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ShipEntity)
    }

    // @@protoc_insertion_point(class_scope:proto.ShipEntity)
    private static final org.tont.proto.PlayerOwnedShip.ShipEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tont.proto.PlayerOwnedShip.ShipEntity();
    }

    public static org.tont.proto.PlayerOwnedShip.ShipEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShipEntity>
        PARSER = new com.google.protobuf.AbstractParser<ShipEntity>() {
      public ShipEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ShipEntity(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ShipEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShipEntity> getParserForType() {
      return PARSER;
    }

    public org.tont.proto.PlayerOwnedShip.ShipEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShipsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Ships)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    java.util.List<org.tont.proto.PlayerOwnedShip.ShipEntity> 
        getShipList();
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    org.tont.proto.PlayerOwnedShip.ShipEntity getShip(int index);
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    int getShipCount();
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    java.util.List<? extends org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder> 
        getShipOrBuilderList();
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder getShipOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.Ships}
   */
  public  static final class Ships extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Ships)
      ShipsOrBuilder {
    // Use Ships.newBuilder() to construct.
    private Ships(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Ships() {
      ship_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Ships(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ship_ = new java.util.ArrayList<org.tont.proto.PlayerOwnedShip.ShipEntity>();
                mutable_bitField0_ |= 0x00000001;
              }
              ship_.add(input.readMessage(org.tont.proto.PlayerOwnedShip.ShipEntity.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ship_ = java.util.Collections.unmodifiableList(ship_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tont.proto.PlayerOwnedShip.internal_static_proto_Ships_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tont.proto.PlayerOwnedShip.internal_static_proto_Ships_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tont.proto.PlayerOwnedShip.Ships.class, org.tont.proto.PlayerOwnedShip.Ships.Builder.class);
    }

    public static final int SHIP_FIELD_NUMBER = 1;
    private java.util.List<org.tont.proto.PlayerOwnedShip.ShipEntity> ship_;
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    public java.util.List<org.tont.proto.PlayerOwnedShip.ShipEntity> getShipList() {
      return ship_;
    }
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    public java.util.List<? extends org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder> 
        getShipOrBuilderList() {
      return ship_;
    }
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    public int getShipCount() {
      return ship_.size();
    }
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    public org.tont.proto.PlayerOwnedShip.ShipEntity getShip(int index) {
      return ship_.get(index);
    }
    /**
     * <code>repeated .proto.ShipEntity ship = 1;</code>
     */
    public org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder getShipOrBuilder(
        int index) {
      return ship_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ship_.size(); i++) {
        output.writeMessage(1, ship_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < ship_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ship_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tont.proto.PlayerOwnedShip.Ships parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.PlayerOwnedShip.Ships parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tont.proto.PlayerOwnedShip.Ships prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Ships}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Ships)
        org.tont.proto.PlayerOwnedShip.ShipsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.PlayerOwnedShip.internal_static_proto_Ships_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.PlayerOwnedShip.internal_static_proto_Ships_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.PlayerOwnedShip.Ships.class, org.tont.proto.PlayerOwnedShip.Ships.Builder.class);
      }

      // Construct using org.tont.proto.PlayerOwnedShip.Ships.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getShipFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (shipBuilder_ == null) {
          ship_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          shipBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tont.proto.PlayerOwnedShip.internal_static_proto_Ships_descriptor;
      }

      public org.tont.proto.PlayerOwnedShip.Ships getDefaultInstanceForType() {
        return org.tont.proto.PlayerOwnedShip.Ships.getDefaultInstance();
      }

      public org.tont.proto.PlayerOwnedShip.Ships build() {
        org.tont.proto.PlayerOwnedShip.Ships result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tont.proto.PlayerOwnedShip.Ships buildPartial() {
        org.tont.proto.PlayerOwnedShip.Ships result = new org.tont.proto.PlayerOwnedShip.Ships(this);
        int from_bitField0_ = bitField0_;
        if (shipBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            ship_ = java.util.Collections.unmodifiableList(ship_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ship_ = ship_;
        } else {
          result.ship_ = shipBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tont.proto.PlayerOwnedShip.Ships) {
          return mergeFrom((org.tont.proto.PlayerOwnedShip.Ships)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tont.proto.PlayerOwnedShip.Ships other) {
        if (other == org.tont.proto.PlayerOwnedShip.Ships.getDefaultInstance()) return this;
        if (shipBuilder_ == null) {
          if (!other.ship_.isEmpty()) {
            if (ship_.isEmpty()) {
              ship_ = other.ship_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureShipIsMutable();
              ship_.addAll(other.ship_);
            }
            onChanged();
          }
        } else {
          if (!other.ship_.isEmpty()) {
            if (shipBuilder_.isEmpty()) {
              shipBuilder_.dispose();
              shipBuilder_ = null;
              ship_ = other.ship_;
              bitField0_ = (bitField0_ & ~0x00000001);
              shipBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getShipFieldBuilder() : null;
            } else {
              shipBuilder_.addAllMessages(other.ship_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tont.proto.PlayerOwnedShip.Ships parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tont.proto.PlayerOwnedShip.Ships) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.tont.proto.PlayerOwnedShip.ShipEntity> ship_ =
        java.util.Collections.emptyList();
      private void ensureShipIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ship_ = new java.util.ArrayList<org.tont.proto.PlayerOwnedShip.ShipEntity>(ship_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.tont.proto.PlayerOwnedShip.ShipEntity, org.tont.proto.PlayerOwnedShip.ShipEntity.Builder, org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder> shipBuilder_;

      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public java.util.List<org.tont.proto.PlayerOwnedShip.ShipEntity> getShipList() {
        if (shipBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ship_);
        } else {
          return shipBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public int getShipCount() {
        if (shipBuilder_ == null) {
          return ship_.size();
        } else {
          return shipBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public org.tont.proto.PlayerOwnedShip.ShipEntity getShip(int index) {
        if (shipBuilder_ == null) {
          return ship_.get(index);
        } else {
          return shipBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder setShip(
          int index, org.tont.proto.PlayerOwnedShip.ShipEntity value) {
        if (shipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShipIsMutable();
          ship_.set(index, value);
          onChanged();
        } else {
          shipBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder setShip(
          int index, org.tont.proto.PlayerOwnedShip.ShipEntity.Builder builderForValue) {
        if (shipBuilder_ == null) {
          ensureShipIsMutable();
          ship_.set(index, builderForValue.build());
          onChanged();
        } else {
          shipBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder addShip(org.tont.proto.PlayerOwnedShip.ShipEntity value) {
        if (shipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShipIsMutable();
          ship_.add(value);
          onChanged();
        } else {
          shipBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder addShip(
          int index, org.tont.proto.PlayerOwnedShip.ShipEntity value) {
        if (shipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShipIsMutable();
          ship_.add(index, value);
          onChanged();
        } else {
          shipBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder addShip(
          org.tont.proto.PlayerOwnedShip.ShipEntity.Builder builderForValue) {
        if (shipBuilder_ == null) {
          ensureShipIsMutable();
          ship_.add(builderForValue.build());
          onChanged();
        } else {
          shipBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder addShip(
          int index, org.tont.proto.PlayerOwnedShip.ShipEntity.Builder builderForValue) {
        if (shipBuilder_ == null) {
          ensureShipIsMutable();
          ship_.add(index, builderForValue.build());
          onChanged();
        } else {
          shipBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder addAllShip(
          java.lang.Iterable<? extends org.tont.proto.PlayerOwnedShip.ShipEntity> values) {
        if (shipBuilder_ == null) {
          ensureShipIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ship_);
          onChanged();
        } else {
          shipBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder clearShip() {
        if (shipBuilder_ == null) {
          ship_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          shipBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public Builder removeShip(int index) {
        if (shipBuilder_ == null) {
          ensureShipIsMutable();
          ship_.remove(index);
          onChanged();
        } else {
          shipBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public org.tont.proto.PlayerOwnedShip.ShipEntity.Builder getShipBuilder(
          int index) {
        return getShipFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder getShipOrBuilder(
          int index) {
        if (shipBuilder_ == null) {
          return ship_.get(index);  } else {
          return shipBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public java.util.List<? extends org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder> 
           getShipOrBuilderList() {
        if (shipBuilder_ != null) {
          return shipBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ship_);
        }
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public org.tont.proto.PlayerOwnedShip.ShipEntity.Builder addShipBuilder() {
        return getShipFieldBuilder().addBuilder(
            org.tont.proto.PlayerOwnedShip.ShipEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public org.tont.proto.PlayerOwnedShip.ShipEntity.Builder addShipBuilder(
          int index) {
        return getShipFieldBuilder().addBuilder(
            index, org.tont.proto.PlayerOwnedShip.ShipEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ShipEntity ship = 1;</code>
       */
      public java.util.List<org.tont.proto.PlayerOwnedShip.ShipEntity.Builder> 
           getShipBuilderList() {
        return getShipFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.tont.proto.PlayerOwnedShip.ShipEntity, org.tont.proto.PlayerOwnedShip.ShipEntity.Builder, org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder> 
          getShipFieldBuilder() {
        if (shipBuilder_ == null) {
          shipBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.tont.proto.PlayerOwnedShip.ShipEntity, org.tont.proto.PlayerOwnedShip.ShipEntity.Builder, org.tont.proto.PlayerOwnedShip.ShipEntityOrBuilder>(
                  ship_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          ship_ = null;
        }
        return shipBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Ships)
    }

    // @@protoc_insertion_point(class_scope:proto.Ships)
    private static final org.tont.proto.PlayerOwnedShip.Ships DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tont.proto.PlayerOwnedShip.Ships();
    }

    public static org.tont.proto.PlayerOwnedShip.Ships getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ships>
        PARSER = new com.google.protobuf.AbstractParser<Ships>() {
      public Ships parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Ships(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Ships> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ships> getParserForType() {
      return PARSER;
    }

    public org.tont.proto.PlayerOwnedShip.Ships getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ShipEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ShipEntity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Ships_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Ships_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020playerShip.proto\022\005proto\"o\n\nShipEntity\022" +
      "\016\n\006shipId\030\001 \001(\t\022\020\n\010shipName\030\002 \001(\t\022\023\n\013des" +
      "cription\030\003 \001(\t\022\r\n\005level\030\004 \001(\005\022\013\n\003exp\030\005 \001" +
      "(\005\022\016\n\006detail\030\006 \001(\t\"(\n\005Ships\022\037\n\004ship\030\001 \003(" +
      "\0132\021.proto.ShipEntityBH\n\016org.tont.protoB\017" +
      "PlayerOwnedShip\252\002$Google.Protobuf.ToNT.P" +
      "layerOwnedShipb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ShipEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ShipEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ShipEntity_descriptor,
        new java.lang.String[] { "ShipId", "ShipName", "Description", "Level", "Exp", "Detail", });
    internal_static_proto_Ships_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Ships_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Ships_descriptor,
        new java.lang.String[] { "Ship", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
